# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export PATH=/usr/local/sbin:$PATH
export PATH=$HOME/.bin:$PATH
export PATH=$HOME/.go/bin:$PATH
export EDITOR=vim
export PAGER="less -FRXS"
export SHOW_AWS_PROMPT=false
export HOMEBREW_BUNDLE_NO_LOCK=true
export AWS_PAGER=
export GROOVY_HOME=/usr/local/opt/groovy/libexec
export GOPATH=$HOME/.go
export ZSH=$HOME/.oh-my-zsh
# export PATH=$(pyenv root)/shims:$PATH

ZSH_CUSTOM=$HOME/.zsh/custom/themes
ZSH_THEME="powerlevel10k/powerlevel10k"
DISABLE_AUTO_TITLE=true
COMPLETION_WAITING_DOTS=true
ZSH_DISABLE_COMPFIX=true

FPATH=$HOME/.zfunc:$FPATH

plugins=(
  zsh_reload
  git
  aws
  docker
  docker-compose
  vagrant
)

source $ZSH/oh-my-zsh.sh

complete -F __start_kubectl k
complete -C /usr/local/bin/terraform terraform
complete -C /usr/local/bin/vault vault

eval "$(nodenv init -)"

for file in $HOME/.zshfunc/*; autoload -Uz $file

alias c="clear"
alias cat=ccat
alias ca=/bin/cat
alias git="noglob git"
alias k=kubectl
alias kx=kubectx
alias kx-unset="kubectl config unset current-context"
alias tf=terraform
alias config-aws="$EDITOR $HOME/.aws/config"
alias config-aws-creds="$EDITOR $HOME/.aws/credentials"
alias config-brew="$EDITOR $HOME/.Brewfile"
alias config-hosts="sudo $EDITOR /etc/hosts"
alias config-git="$EDITOR $HOME/.gitconfig"
alias config-git-ignore="$EDITOR $HOME/.gitignore"
alias config-kube="$EDITOR $HOME/.kube/config"
alias config-maven="$EDITOR $HOME/.m2/settings.xml"
alias config-ssh="$EDITOR $HOME/.ssh/config"
alias config-ssh-work="$EDITOR $HOME/.ssh/config_work"
alias config-ssh-hosts="$EDITOR $HOME/.ssh/known_hosts"
alias config-vim="$EDITOR $HOME/.vimrc"
alias config-zsh="$EDITOR $HOME/.zshrc"
alias config-zsh-theme="$EDITOR $HOME/.zsh/custom/themes/dotfiles.zsh-theme"
alias aws-whoami="aws sts get-caller-identity"
alias wmip="curl ipv4.icanhazip.com"
# alias ap="pyenv exec ansible-playbook"
# alias env-init-python='pyenv virtualenv 3.8.0 ${PWD##*/} && pyenv local ${PWD##*/}'
alias env-gpg-reset="gpg-connect-agent updatestartuptty /bye"
alias env-gpg-learn="gpg-connect-agent 'scd serialno' 'learn --force' /bye"
alias env-dns-flush="dscacheutil -flushcache && sudo killall -HUP mDNSResponder"
alias cdpp="cd $HOME/Projects/personal"
alias cdpw="cd $HOME/Projects/work"
alias sbp="cd $HOME/Projects/personal/sandbox"
alias sbw="cd $HOME/Projects/work/sandbox"
alias update-brew-bundle="brew bundle dump --global --force"
alias update-brew="brew bundle cleanup --force --global && brew update && brew upgrade && brew cleanup"
alias update-all="upgrade_oh_my_zsh && update-brew"
alias main="git checkout main && git pull"
alias master="git checkout master && git pull"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
source /opt/homebrew/opt/powerlevel10k/powerlevel10k.zsh-theme
# eval "$(pyenv init -)"
# # export PYENV_ROOT="$HOME/.pyenv"
# # export PATH="$PYENV_ROOT/bin:$PATH"
# # if command -v pyenv 1>/dev/null 2>&1; then
# #   eval "$(pyenv init -)"
# # fi
# eval "$(pyenv virtualenv-init -)"

export PYENV_ROOT="$HOME/.pyenv" 
export PATH="$PYENV_ROOT/bin:$PATH" 
eval "$(pyenv init --path)" 
eval "$(pyenv init -)"
