export PATH=/usr/local/sbin:$PATH
export PATH=$HOME/.bin:$PATH
export PATH=$HOME/.go/bin:$PATH
export EDITOR=vim
export PAGER="less -FRXS"
export PYENV_VIRTUALENV_DISABLE_PROMPT=true
export SHOW_AWS_PROMPT=false
export HOMEBREW_BUNDLE_NO_LOCK=true
export AWS_PAGER=
export GROOVY_HOME=/usr/local/opt/groovy/libexec
export GOPATH=$HOME/.go
export ZSH=$HOME/.oh-my-zsh

ZSH_CUSTOM=$HOME/.zsh/custom
ZSH_THEME="dotfiles"
DISABLE_AUTO_TITLE=true
COMPLETION_WAITING_DOTS=true
ZSH_DISABLE_COMPFIX=true

FPATH=$HOME/.zfunc:$FPATH

plugins=(
  zsh_reload
  git
  aws
  docker
  docker-compose
  vagrant
  pyenv
)

source $ZSH/oh-my-zsh.sh

complete -F __start_kubectl k
complete -C /usr/local/bin/terraform terraform
complete -C /usr/local/bin/vault vault

eval "$(nodenv init -)"
eval "$(pyenv init -)"

for file in $HOME/.zshfunc/*; autoload -Uz $file

alias c="clear"
alias cat=ccat
alias ca=/bin/cat
alias git="noglob git"
alias k=kubectl
alias kx=kubectx
alias kx-unset="kubectl config unset current-context"
alias tf=terraform
alias config-aws="$EDITOR $HOME/.aws/config"
alias config-aws-creds="$EDITOR $HOME/.aws/credentials"
alias config-brew="$EDITOR $HOME/.Brewfile"
alias config-hosts="sudo $EDITOR /etc/hosts"
alias config-git="$EDITOR $HOME/.gitconfig"
alias config-git-ignore="$EDITOR $HOME/.gitignore"
alias config-kube="$EDITOR $HOME/.kube/config"
alias config-maven="$EDITOR $HOME/.m2/settings.xml"
alias config-ssh="$EDITOR $HOME/.ssh/config"
alias config-ssh-work="$EDITOR $HOME/.ssh/config_work"
alias config-ssh-hosts="$EDITOR $HOME/.ssh/known_hosts"
alias config-vim="$EDITOR $HOME/.vimrc"
alias config-zsh="$EDITOR $HOME/.zshrc"
alias config-zsh-theme="$EDITOR $HOME/.zsh/custom/themes/dotfiles.zsh-theme"
alias aws-whoami="aws sts get-caller-identity"
alias wmip="curl ipv4.icanhazip.com"
alias ap="pyenv exec ansible-playbook"
alias env-init-python='pyenv virtualenv 3.8.0 ${PWD##*/} && pyenv local ${PWD##*/}'
alias env-gpg-reset="gpg-connect-agent updatestartuptty /bye"
alias env-gpg-learn="gpg-connect-agent 'scd serialno' 'learn --force' /bye"
alias env-dns-flush="dscacheutil -flushcache && sudo killall -HUP mDNSResponder"
alias cdpp="cd $HOME/Projects/personal"
alias cdpw="cd $HOME/Projects/work"
alias sbp="cd $HOME/Projects/personal/sandbox"
alias sbw="cd $HOME/Projects/work/sandbox"
alias update-brew-bundle="brew bundle dump --global --force"
alias update-brew="brew bundle cleanup --force --global && brew update && brew upgrade && brew cleanup"
alias update-all="upgrade_oh_my_zsh && update-brew"
alias main="git checkout master && git pull"
